### ISSUE TITLE
About the calculation of t1/2 value

### ISSUE THREAD

**Issue by lbwfff** [reedssorenson/RNAdecay#5]
Hi, 

Thanks for the excellent tool, I still have some questions about the use of the RNAdecay package. Through a series of calculations, we end up with a result file similar to RNAdecay::results, but I still don't know how to calculate to get the t1/2 value. I see t1/2 in the picture drawn by the hl_plot function, but if I want to calculate the t1/2 of a large number of genes in batches, how can I calculate it?

Thanks,

LeeLee

**Comment by reedssorenson** [comment]
Hi LeeLee, 
I'm sorry, I haven't checked in on these messages here for a long time. You have probably already found the answer to your question, but here it is: 
half-life =  ln(2)/decay_rate^-1
Reed
